### PR TITLE
add option to be able to specify the ipconfig path.

### PR DESCRIPTION
**Pull request by vsc55**

### CODE REVIEW

**Comment by BlakeGardner** [comment]
@vsc55 thanks for the contribution, can you put the composer.json back to the original? It will break installs.

**Comment by vsc55** [comment]
Hi @BlakeGardner, it's already modified. 
It may be a good idea to specify in the composer.json keyword that it is a UNIX / LINUX only version. 
`"keywords": ["MAC", "Address", "IP", "ifconfig", "DHCP", "UNIX", "LINUX"],`

**Comment by vsc55** [comment]
Hi @BlakeGardner is there a problem with the pull?

**Comment by kapilsangoma** [comment]
Hi @BlakeGardner Is it possible for you to merge this PR? We have integrated your library into our open source product i.e. FreePBX  and this issue is affecting many of our users. appreciate your prompt reply.

Thanks.
Kapil

**Comment by BlakeGardner** [comment]
Hey @kapilsangoma and @vsc55 will be merging today, sorry for the delay due to the holidays!

**Comment by BlakeGardner** [comment]
@kapilsangoma -- @vsc55 version `2.2.0` is up on packagist now

**Comment by kapilsangoma** [comment]
Thanks a lot @BlakeGardner and Happy New Year 2022 !!

**Pull request merged**
